In [3]:
import xarray as xr
import numpy as np

In [4]:
da = xr.DataArray(
    np.random.rand(4,4),
    dims=['x','y'],
)
da

<xarray.DataArray (x: 4, y: 4)>
array([[0.89435016, 0.24610001, 0.58972514, 0.5875443 ],
       [0.54683982, 0.4776781 , 0.09551029, 0.9144584 ],
       [0.51382771, 0.89771929, 0.46316564, 0.75211002],
       [0.54972637, 0.64871325, 0.39554443, 0.50038317]])
Dimensions without coordinates: x, y

In [5]:
da = da.roll(y=2)
da

<xarray.DataArray (x: 4, y: 4)>
array([[0.58972514, 0.5875443 , 0.89435016, 0.24610001],
       [0.09551029, 0.9144584 , 0.54683982, 0.4776781 ],
       [0.46316564, 0.75211002, 0.51382771, 0.89771929],
       [0.39554443, 0.50038317, 0.54972637, 0.64871325]])
Dimensions without coordinates: x, y

In [6]:
da2 = da.reindex(y=da.y[::-1])
da2

<xarray.DataArray (x: 4, y: 4)>
array([[0.58972514, 0.5875443 , 0.89435016, 0.24610001],
       [0.09551029, 0.9144584 , 0.54683982, 0.4776781 ],
       [0.46316564, 0.75211002, 0.51382771, 0.89771929],
       [0.39554443, 0.50038317, 0.54972637, 0.64871325]])
Coordinates:
  * y        (y) int64 3 2 1 0
Dimensions without coordinates: x

In [7]:
da2.sortby('y')

<xarray.DataArray (x: 4, y: 4)>
array([[0.24610001, 0.89435016, 0.5875443 , 0.58972514],
       [0.4776781 , 0.54683982, 0.9144584 , 0.09551029],
       [0.89771929, 0.51382771, 0.75211002, 0.46316564],
       [0.64871325, 0.54972637, 0.50038317, 0.39554443]])
Coordinates:
  * y        (y) int64 0 1 2 3
Dimensions without coordinates: x